{% set name = "inflate64" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inflate64-{{ version }}.tar.gz
  sha256: b52dd8fefd2ba179e5dfa18d6eca7e2fc822584616271c039d5ef1f9ca90c71c

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=45
    - setuptools-scm >=6.0.1
  run:
    - importlib-metadata  # [py<38]
    - python

test:
  imports:
    - inflate64
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/inflate64/
  summary: deflate64 compression/decompression library
  license: LGPL-2.1-or-later
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - sarthakpati
